namespace: vpmeals

app:
  name: vpmeals
  replicas: 3

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx

service:
  type: ClusterIP
  port: 80

volumes:
  mountPath: /usr/share/nginx/html
